name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: npm install

